# Setup
title: üë©üèª‚ÄçüíªÌò∏ÎπµÏù¥ Í≥µÍ∞Ñ
description: AI for Security
url: https://AIRS12.github.io
avatar: /profile.jpg
paginate: 5
permalink: pretty
cover_image: /white.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
instagram:
  username: greena.9
social:
  name: greena
  links:
    - https://github.com/AIRS12
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Not Pure Pools
  url: https://github.com/AIRS12/
  email: greena@korea.ac.kr
